# Generated by Django 5.2.13 on 2026-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/category/default_category.jpg', null=True, upload_to='category/'),
        ),
    ]
