# Generated by Django 5.2.13 on 2026-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='media/logos/shop.jpg', null=True, upload_to='logos/'),
        ),
    ]
