# Generated by Django 5.2.13 on 2026-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='media/product/product.png', null=True, upload_to='product/'),
        ),
    ]
